num_epochs: 15
early_stop_offset: 50
batch_size: 1000
memory_dim: 128
time_dim: 128
embedding_dim: 512
use_l1: False
use_l2: False
use_dropout: False
l2_lambda: 0
l1_lambda: 0.0001 
dropout: 0.2
lamb: 0